package airmord;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FeedbackObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Email")
   private java.lang.String email;
   @org.kie.api.definition.type.Label(value = "Message")
   private java.lang.String message;

   public FeedbackObject()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getMessage()
   {
      return this.message;
   }

   public void setMessage(java.lang.String message)
   {
      this.message = message;
   }

   public FeedbackObject(java.lang.String name, java.lang.String email,
         java.lang.String message)
   {
      this.name = name;
      this.email = email;
      this.message = message;
   }

}