package airmord;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserAccount implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public UserAccount() {
    }

}